//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisabilityAdvantage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildCount
    {
        public int Id { get; set; }
        public string SCHOOL_YR { get; set; }
        public string LEVEL_CODE { get; set; }
        public string DIV_NUM { get; set; }
        public string DIV_NAME { get; set; }
        public string SCH_NUM { get; set; }
        public string SCH_NAME { get; set; }
        public string GRADE_CODE { get; set; }
        public string FEDERAL_RACE_CODE { get; set; }
        public string GENDER { get; set; }
        public string DISABILITY_FLAG { get; set; }
        public string LEP_FLAG { get; set; }
        public string DISADVANTAGED_FLAG { get; set; }
        public string PRIMARY_DISABILITY_TYPE { get; set; }
        public int DEC1_CNT { get; set; }
    }
}
