//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisabilityAdvantage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Disabilities = new HashSet<Disability>();
        }
    
        public int Number { get; set; }
        public int SchoolId { get; set; }
        public int GradeNumber { get; set; }
        public int AcademicYearNumber { get; set; }
        public int StudentCount { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual School School { get; set; }
        public virtual ICollection<Disability> Disabilities { get; set; }
    }
}
