/****** Object:  Table [dbo].[Division]    Script Date: 01/29/2013 01:24:33 ******/
SET IDENTITY_INSERT [dbo].[Division] ON
INSERT [dbo].[Division] ([Number], [Name]) VALUES (1, N'Accomack County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (2, N'Albemarle County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (101, N'Alexandria City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (3, N'Alleghany County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (4, N'Amelia County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (5, N'Amherst County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (6, N'Appomattox County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (7, N'Arlington County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (8, N'Augusta County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (9, N'Bath County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (10, N'Bedford County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (11, N'Bland County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (12, N'Botetourt County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (102, N'Bristol City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (13, N'Brunswick County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (14, N'Buchanan County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (15, N'Buckingham County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (103, N'Buena Vista City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (16, N'Campbell County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (17, N'Caroline County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (18, N'Carroll County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (19, N'Charles City County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (20, N'Charlotte County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (104, N'Charlottesville City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (136, N'Chesapeake City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (21, N'Chesterfield County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (22, N'Clarke County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (202, N'Colonial Beach')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (106, N'Colonial Heights City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (107, N'Covington City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (23, N'Craig County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (24, N'Culpeper County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (25, N'Cumberland County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (108, N'Danville City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (26, N'Dickenson County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (27, N'Dinwiddie County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (28, N'Essex County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (29, N'Fairfax County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (109, N'Falls Church City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (30, N'Fauquier County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (31, N'Floyd County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (32, N'Fluvanna County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (135, N'Franklin City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (33, N'Franklin County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (34, N'Frederick County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (110, N'Fredericksburg City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (111, N'Galax City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (35, N'Giles County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (36, N'Gloucester County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (37, N'Goochland County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (38, N'Grayson County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (39, N'Greene County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (40, N'Greensville County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (41, N'Halifax County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (112, N'Hampton City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (42, N'Hanover County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (113, N'Harrisonburg City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (43, N'Henrico County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (44, N'Henry County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (45, N'Highland County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (114, N'Hopewell City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (46, N'Isle of Wight County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (49, N'King and Queen County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (48, N'King George County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (50, N'King William County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (51, N'Lancaster County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (52, N'Lee County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (137, N'Lexington City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (53, N'Loudoun County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (54, N'Louisa County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (55, N'Lunenburg County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (115, N'Lynchburg City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (56, N'Madison County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (143, N'Manassas City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (144, N'Manassas Park City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (116, N'Martinsville City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (57, N'Mathews County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (58, N'Mecklenburg County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (59, N'Middlesex County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (60, N'Montgomery County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (62, N'Nelson County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (63, N'New Kent County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (117, N'Newport News City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (118, N'Norfolk City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (65, N'Northampton County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (66, N'Northumberland County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (119, N'Norton City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (67, N'Nottoway County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (68, N'Orange County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (69, N'Page County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (70, N'Patrick County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (120, N'Petersburg City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (71, N'Pittsylvania County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (142, N'Poquoson City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (121, N'Portsmouth City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (72, N'Powhatan County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (73, N'Prince Edward County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (74, N'Prince George County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (75, N'Prince William County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (77, N'Pulaski County')
GO
print 'Processed 100 total records'
INSERT [dbo].[Division] ([Number], [Name]) VALUES (122, N'Radford City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (78, N'Rappahannock County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (123, N'Richmond City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (79, N'Richmond County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (124, N'Roanoke City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (80, N'Roanoke County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (81, N'Rockbridge County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (82, N'Rockingham County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (83, N'Russell County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (139, N'Salem City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (84, N'Scott County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (85, N'Shenandoah County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (86, N'Smyth County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (87, N'Southampton County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (88, N'Spotsylvania County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (89, N'Stafford County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (126, N'Staunton City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (127, N'Suffolk City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (90, N'Surry County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (91, N'Sussex County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (92, N'Tazewell County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (128, N'Virginia Beach City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (93, N'Warren County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (94, N'Washington County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (130, N'Waynesboro City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (207, N'West Point')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (95, N'Westmoreland County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (131, N'Williamsburg-James City County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (132, N'Winchester City')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (96, N'Wise County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (97, N'Wythe County')
INSERT [dbo].[Division] ([Number], [Name]) VALUES (98, N'York County')
SET IDENTITY_INSERT [dbo].[Division] OFF
